services:
  # --- Infrastucture Services ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      # 외부(호스트 머신)에서 Kafka에 접속하기 위한 포트
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # 컨테이너 내부 통신용 리스너
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  mariadb:
    image: mariadb:10.11
    container_name: guestbook_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=guestbook_db
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: guestbook_mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always

  # --- Application Services ---
  backend:
    build: ./backend
    container_name: guestbook_backend
    depends_on:
      - kafka
    environment:
      - MARIADB_URL=mysql+pymysql://user:password@mariadb/guestbook_db
      # Kafka 컨테이너의 내부 리스너 주소를 사용
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: guestbook_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  # --- Consumer Services ---
  mariadb_consumer:
    build: ./consumers/mariadb
    container_name: mariadb_consumer
    depends_on:
      - kafka
      - mariadb
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MARIADB_URL=mysql+pymysql://user:password@mariadb/guestbook_db
    restart: always

  mongodb_consumer:
    build: ./consumers/mongodb
    container_name: mongodb_consumer
    depends_on:
      - kafka
      - mongodb
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URL=mongodb://mongodb:27017/
    restart: always

volumes:
  mariadb_data:
  mongo_data: