version: '3.8'

services:
  # 백엔드 서비스 (FastAPI)
  backend:
    build: ./backend
    container_name: guestbook_backend
    # 개발 중 코드 변경 시 자동 재시작을 원하면 아래 주석을 해제하세요.
    # volumes:
    #   - ./backend:/code
    ports:
      - "8000:8000"

  # 프론트엔드 서비스 (React + Nginx)
  frontend:
    build: ./frontend
    container_name: guestbook_frontend
    ports:
      - "3000:80" # 호스트의 3000번 포트를 컨테이너의 80번 포트와 연결
    depends_on:
      - backend # 백엔드가 먼저 실행되도록 보장